apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-rs
spec:
  replicas: 7
  selector:
    matchExpressions:
      - { key: env,  operator: In,  values: [ production ] }
      
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
        dc: "2"
        region: IN
    spec:
      containers:
      - name: myweb-con
        image: httpd 